name: publish
on: 
  workflow_dispatch:
  push:
   branches:
           - main
 
env:
 AZURE_WEBAPP_NAME: appbookstore
 AZURE_WEBAPP_PACKAGE_PATH: " ./publish "
           
jobs:
 publish:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   
   - name: setup .NET
     uses: actions/setup-dotnet@v3
     with: 
       dotnet-version: ' 6.0.x '
   
   - name: Build
     run: dotnet build ./BookStoreApp/BookStoreApp.sln --configuration Release 
     
   - name: Publish
     run: dotnet publish ./BookStoreApp/BookStoreApp.sln --configuration Release 
     
   - name: Deployment
     uses: actions/webapps-deploy@v2
     
     with: 
       app-name: ${{ env.AZURE_WEBAPP_NAME }}
       publish-profile:  ${{ secrets.PUBLISH_PROFILE }}
       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
       
       
     
     
   
       
   
   
   

