name: publish
on: 
  workflow_dispatch:
  push:
   branches:
           - main
           
jobs:
 publish:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   
   - name: setup .NET
     uses: actions/setup-dotnet@v3
     with: 
       dotnet-version: ' 6.0.x '
       
   - name: Restore
     run: dotnet restore ./BookStoreApp.sln
     
   - name: Build
     run: dotnet build ./BookStoreApp.sln --configuration Release --no restore
     
   - name: Publish
     run: dotnet publish ./BookStoreApp.sln --configuration Release --no restore
     
     
   
       
   
   
   

